# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape configuration for our application
  - job_name: "nextgen"
    static_configs:
      - targets: ["localhost:8010"]
        labels:
          service: "nextgen"

  # System monitoring
  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          instance: "localhost"
